### PR TITLE
H64 options 

### PR DESCRIPTION
**Pull request by BeerMoneyMotorsports**

### CODE REVIEW

**Comment by rusefillc** [comment]
spaces in files names are a bit risky shall we try a dash instead?

**Comment by rusefillc** [comment]
I am not excited about two different files with same name but different extension? please confirm that this is the intention

overall list of touched files https://github.com/rusefi/rusefi_documentation/pull/159/files is really odd

 BIN +2.54 MB Hardware/Hellen/hellen64na6-b.jpeg 
 BIN +1.08 MB Hardware/Hellen/hellen64na6-b.jpg

**Comment by BeerMoneyMotorsports** [comment]
I have added dash for H64-Options.  
The .jpg is the old file.  i did not see the difference when previously uploading.  BIN +1.08 MB Hardware/Hellen/hellen64na6-b.jpg can be deleted.

**Comment by rusefillc** [comment]
there is no way for me to accept partial PR

please create new one only with files you mean to change

please reference "files changed" and confirm number of files you intend to change

**Pull request closed without merging**
