### PR TITLE
Add table of features

### PR DESCRIPTION
**Pull request by chuckwagoncomputing**
This isn't a complete list of features, and I'm not sure I even got everything right, but it's a start.
Someone who knows more about the current state of things than I do should add some of these things:
what algos are supported, e.g. speed density, alpha-n, etc.
VVT support?
Auto tuning?
Wideband control?

### CODE REVIEW

**Comment by chuckwagoncomputing** [comment]
Ignore the commit history. :)

**Comment by mck1117** [comment]
I have mixed feelings about including so many things we don't support

**Comment by chuckwagoncomputing** [comment]
Oh, and what about multiple map switching?

**Comment by chuckwagoncomputing** [comment]
I included things that seemed to be asked about often on the forums.
What are the downsides to including them?

**Comment by chuckwagoncomputing** [comment]
There's also this wiki page, which doesn't seem to be related to features, and also seems to be incomplete:
https://github.com/rusefi/rusefi/wiki/What_rusEFI_Cannot_Do

**Pull request merged**
