### PR TITLE
update for doc repo "protected branch" change

### PR DESCRIPTION
**Pull request by mi-hol**

### CODE REVIEW

**Review by chuckwagoncomputing — CHANGES_REQUESTED** [review]
It cannot be a .md file or lint will fail.

**Comment by mi-hol** [comment]
> It cannot be a .md file or lint will fail.

In order to prevent this issue  I moved it to dir "wiki_tools".
Does that not prevent issues?

**Comment by chuckwagoncomputing** [comment]
No. All .md files are checked when a file is removed, added, or renamed.

**Comment by mi-hol** [comment]
From my view  "All .md files are checked" does NOT mean "All .md files in ALL SUB-DIRECTORIES are checked"!
In case it is implemented this is unexpected behavior (remember my comment regarding observability?).

The directory structure was flattened on purpose, therefore "All .md files are checked" should be limited to the directory "rusefi_documentation" too.

**Comment by chuckwagoncomputing** [comment]
> Implicitly doing something like "All .md files in ALL SUB-DIRECTORIES are checked" is NEVER a good implementation!

Why not?

**Review by chuckwagoncomputing — APPROVED** [review]

**Pull request merged**
