### PR TITLE
Update FAQ-Basic-Wiring-and-Connections.md

### PR DESCRIPTION
**Pull request by EA11R**
Fixed table not being shown on web wiki

Added trigger , knock sensor wiring information.

### CODE REVIEW

**Comment by rusefillc** [comment]
@EA11R please note red Lint validation https://github.com/rusefi/rusefi_documentation/actions/runs/9260197083/job/25473535991?pr=507 

@EA11R please fix code style to have lint green

**Comment by rusefillc** [comment]
@EA11R progress it's just asking a couple of empty lines!

**Comment by EA11R** [comment]
Yeah I noticed I will adjust them accordingly right now

**Comment by EA11R** [comment]
lint pass

**Pull request merged**
