### PR TITLE
Flatten

### PR DESCRIPTION
**Pull request by chuckwagoncomputing**
I started moving images to the Images directory, but I decided partway through it was too much work for me today.

### CODE REVIEW

**Comment by rusefillc** [comment]
Hold on, do we need to flatten images at all?

**Comment by chuckwagoncomputing** [comment]
Now that I'm actually testing this, I can't tell that it has actually helped anything. But it's also late and my brain is no longer working properly. Don't merge yet.

**Comment by nmschulte** [comment]
> Hold on, do we need to flatten images at all?

I gathered that assets (like images) don't need flattened, both from articles about the web, and my tests of how GH wiki routing works:

> - same-named pages go wonk; first page clobbers the others in routing
> - linking pages in sub-dirs obv. doesn't work (correct path, but routing doesn't support and so 404)
> - repo-root relative link URLs don't work (/page resolves to [github.com/page](http://github.com/page) vs [github.com/repo/wiki/page](http://github.com/repo/wiki/page))
>   - however, repo-root relative link URLs do resolve as expected for links to files in sub-dirs (so long as it's not a "page," I guess -- e.g. it could link to an asset (.log) or image-file
> 
> image
> all this to confirm ... using GH wiki we should use flat-dir structure for pages

**Comment by chuckwagoncomputing** [comment]
We don't need to flatten images, I was just trying to reduce the chaos.

**Comment by chuckwagoncomputing** [comment]
@nmschulte Did you find that a flat directory structure worked better for trailing slashes? I was sure that I had, but now I can't make it work.

**Comment by nmschulte** [comment]
> Did you find that a flat directory structure worked better for trailing slashes?

In my quick tests just now, I'm not sure why we'd ever want to use a trailing slash in a URL (for links or otherwise):
- a request with a trailing slash that doesn't map to a page name is redirected to `raw.githubusercontent.com`, which is how images/assets are served: e.g. https://raw.githubusercontent.com/wiki/nmschulte/rusefi/xyz-nms-dir/nms.md (orhttps://raw.githubusercontent.com/wiki/rusefi/rusefi/Images/Latest_bundle_border.png)
  - `raw.githubusercontent.com` doesn't serve directory listings: e.g. https://raw.githubusercontent.com/wiki/nmschulte/rusefi/Images/ is 404
- a request with a trailing slash that maps to a page name doesn't redirect, but loads that page: e.g. https://github.com/nmschulte/rusefi/wiki/nms/

**Comment by chuckwagoncomputing** [comment]
We don't _want_ a trailing slash in our URLs, but the happen somehow. We've been having people report issues for a long time that end up being because they loaded a page with a trailing slash.

**Comment by chuckwagoncomputing** [comment]
One advantage of a flat structure is that ../ relative links will work in both GH and MkDocs, but name-only links work in both places anyhow.

**Comment by chuckwagoncomputing** [comment]
@rusefillc As far as I can tell, the biggest thing this changes is in our brains.
My brain finds a hierarchical folder structure easier to work with.
Your brain doesn't like that  "/Technical/All-Supported-Triggers.md" gets turned into "All-Supported-Triggers".

When it comes down to it, I don't care much which way this goes. I'll make this a normal PR again, and you can either close it or merge it.

**Comment by rusefillc** [comment]
This PR does too much - it flattens both .md and images

Can we please close this one and only flatten .md files?

**Pull request closed without merging**
