### PR TITLE
obsolete IMGUR as image hoster

### PR DESCRIPTION
**Pull request by mi-hol**

### CODE REVIEW

**Comment by mi-hol** [comment]
@mck1117 @chuckwagoncomputing would you perhaps have the images required to complete the ToDos?

ToDo: 
1. add correct polarity scope image
2. add wrong polarity scope image

**Comment by mi-hol** [comment]
@chuckwagoncomputing  as I fail to see the root cause of lint error, would you perhaps see it?
```
Run bash ./wiki-tools/lint.sh
In ./Trigger-Configuration-Guide.md:
Images/trigger_VR_sensor_correct_polarity
     [1](https://github.com/rusefi/rusefi_documentation/actions/runs/4472185202/jobs/7858172465#step:4:1)	./Images/trigger_VR_sensor_correct_polarity.png
In ./Trigger-Configuration-Guide.md:
Images/trigger_VR_sensor_wrong_polarity
     1	./Images/trigger_VR_sensor_wrong_polarity.png
Error: Process completed with exit code 1.

**Comment by chuckwagoncomputing** [comment]
File extensions

**Comment by mi-hol** [comment]
> File extensions

missing for images. 
OMG 2 weeks exposed to sun light clearer my memory :(

**Pull request merged**
