### PR TITLE
Move docs from rusefi/rusefi

### PR DESCRIPTION
**Pull request by chuckwagoncomputing**

### CODE REVIEW

**Comment by mck1117** [comment]
do we even care about these random png images from 2013?

**Comment by mi-hol** [comment]
> do we even care about these random png images from 2013?

you mean the ones in /Images/MAP sensor/ right?

I searched for references to this dir in both repos but had no hits.
Seems to be old "trash" that can be removed without impact

**Comment by rusefillc** [comment]
Yes, trash chould be removed

**Comment by rusefillc** [comment]
What about less trashy files? Either we break links or these are unused and should be deleted?

**Comment by mi-hol** [comment]
> these are unused and should be deleted?

they are currently unlinked in wiki but should be linked from my view as the next step

**Comment by mi-hol** [comment]
@rusefillc many valuable docs are currently unlinked  https://github.com/rusefi/rusefi_documentation/issues/297 is the task to fix this issue via "Identify "orphaned" documents having no references to index / Table of Content"

**Comment by chuckwagoncomputing** [comment]
Closing these because I don't feel like swimming upstream today.

**Pull request closed without merging**
