### PR TITLE
Delete shop-ru.md

### LINKED ISSUE #406: make rusEFI shopping consistent
Currently several URL targets are used, leading to confusion

```
[rusEFI store](https://www.shop.rusefi.com/shop) seems the only correct one
```
incorrect seem to be:
```
[<https://www.tindie.com/stores/russian/> our store]

[Ebay Store](https://www.ebay.com/itm/333532119947)
[eBay Store](http://www.ebay.com/usr/rusefi)
```

To fix the links I need above findings confirmed

### PR DESCRIPTION
**Pull request by mi-hol**
closes #406

### CODE REVIEW

**Comment by rusefillc** [comment]
@mi-hol better part merged as https://github.com/rusefi/rusefi_documentation/commit/067d09816b0f3af7f1e82c1925eeb22bab8ee008

shop-ru has to please stay

**Comment by mi-hol** [comment]
> shop-ru has to please stay

It would be great to know the reason(s) to avoid the same issue in future

**Comment by rusefillc** [comment]
shop-ru has unique content targeting RU market with special payment and delivery considerations, also URL of Russian WhatsApp group. In light of shop-ru having unique content it looks like it should stay?

**Comment by mi-hol** [comment]
> In light of shop-ru having unique content it looks like it should stay?

From my view a definitive NO, because a commercial & special setup should be addressed in https://shop.rusefi.com/ only

**Comment by mck1117** [comment]
>  special setup

https://en.wikipedia.org/wiki/2022_Russian_invasion_of_Ukraine

**Pull request closed without merging**
